# Generated by Django 5.2.9 on 2025-12-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OdooConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='http://localhost:8069', verbose_name="URL de l'instance Odoo")),
                ('db', models.CharField(max_length=100, verbose_name='Nom de la base de données Odoo')),
                ('username', models.CharField(max_length=100, verbose_name="Email de l'utilisateur Odoo")),
                ('password', models.CharField(max_length=100, verbose_name="Mot de passe de l'utilisateur Odoo")),
            ],
        ),
    ]
